### PR TITLE
feat: add ghostty theme

### PR DESCRIPTION
**Pull request by metalelf0**
Add a ghostty terminal theme with no clown fiesta colors.

### CODE REVIEW

**Comment by aktersnurra** [comment]
Thanks for the contribution, please add this PR [here](https://github.com/no-clown-fiesta/no-clown-fiesta.ghostty) instead.

**Comment by metalelf0** [comment]
Hi, I think you should add at least a README file to that repo for me to clone it and send a PR. It seems you can't clone empty repos.

**Comment by aktersnurra** [comment]
Ok, you will have to fork it, add the remote on your machine/repo, then push the changes, then open a PR against that repo (or along those lines). But if you want to I can add this theme if it is more convenient?

**Comment by metalelf0** [comment]
Yeah I know how it works, but it seems I can't fork the repo if it's empty.

**Comment by aktersnurra** [comment]
Aha, I did not even check that. I added a readme now.

**Pull request closed without merging**
